name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    # Remove this section if no dependencies
    # - name: Install dependencies
    #   run: |
    #     pip install -r requirements.txt
    - name: Run Python script
      run: |
        python calculator.py  # Replace this with your script

